// <auto-generated />
namespace QASystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class u_user2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(u_user2));
        
        string IMigrationMetadata.Id
        {
            get { return "201603130750523_u_user2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
